---
- name: playbook to play with facts
  hosts: localhost
  vars:
    - temp_pass: "{{ 'password' | password_hash('sha512') }}"
  tasks:
    - name: display DNS and IPs
      debug:
        var: temp_pass
...
