ips:
  hosts:
    192.168.3.[21:23]:
      ansible_become_pass: vagrant
web:
  hosts:
    centos[1:3]:
      ansible_become_pass: vagrant
local:
  hosts:
    localhost:
      ansible_connection: local

lab:
  children:
    web:
    local:
  
